### PR TITLE
equalsAndHashCode

### PR DESCRIPTION
**Pull request by twillouer**
Hi,

I need this for my unit tests.

Is it possible to quickly review it, and, if it's fine for you, to generate a new revision ?

(can we consider use "projectlombok" to generate all of this boilerplate things (toString, equals, hashCode) ?

### CODE REVIEW

**Comment by grundid** [comment]
I'm not sure, but source code that is only needed in unit tests should stay in unit tests. Why add it into production code?

**Comment by twillouer** [comment]
Hi,

you have bean (like LngLatAlt) who cannot be equals.

If you need to store (in production code) a Set of LngLatAlt, they will not be unique in business point of view because equals and hashcode are not redifined.

All your objets cannot be "equals", even they have same values.

In my UnitTest, I need to know if, when I store a Feature into MongoDB, I can retrieve the same "business" object as I store it.

So, it's why I say "I need it for my UnitTest", but in business point of view, it's a bit strange to have object you can't compare

**Comment by twillouer** [comment]
I understand your concern, but if you can quickly fix me on the status of the PR, I need GeoJSon in fongo and I need equals/hashCode and toString :)

**Comment by twillouer** [comment]
Thanks !

**Comment by grundid** [comment]
Thank you for your contribution. I've merged all your pull requests. Right now I have an issue with the release plugin but I'm going to fix it tomorrow and release the update to maven central.

**Comment by twillouer** [comment]
Let me know if I can help !

**Comment by grundid** [comment]
Thanks again. After updating most of the maven plugins the release finally went through. It should be visible on central within a few hours. Version 1.3

**Comment by twillouer** [comment]
it works already from 2 ou 3 hours :+1:

**Pull request merged**
