### PR TITLE
lat,lon,alt uses BigDecimal instead of double

### PR DESCRIPTION
**Pull request by dosten-xx**
Great work on the geojson code.  I made a version that uses BigDecimal instead of double.  Give it a look.

### CODE REVIEW

**Comment by grundid** [comment]
Thank you, but could you explain your motivation behind this? Why BigDecimal and not Double? Why should be deal with null objects?

**Comment by dosten-xx** [comment]
I prefer the accuracy of BigDecimal for coordianates.  Null's would be empty strings if you are allowing for undefined coordinates.  Undefined coords could also be treated as an error.

**Comment by twillouer** [comment]
@dosten-xx I understand why BigDecimal are better than double. But lat/long have already an accuracy, who is far away worste than "double" :)

Btw, your modification make a big change in the api (everybody is mandatory to upgrade all his code to change double to BigDecimal).
I try to check in GeoJSon documentation (http://geojson.org/geojson-spec.html#positions) but documentation doesn't mention anything.

For your information, MongoDB, Google (with googlemaps), JTS, use double for lat/long.

**Comment by grundid** [comment]
I agree with twillouer. The precision of a BigDecimal is unnecessary for lon/lat.

**Pull request closed without merging**
